[package]
name = "file-serve"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
rand = "0.9.2"
rusqlite = { version = "0.36.0", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
